// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUd5cXGtmnTkk5n2zMwsxA_bcb0J5gl8',
    appId: '1:243663523925:web:6daf7875beeaf4427d44dc',
    messagingSenderId: '243663523925',
    projectId: 'surf-para-baixinhos',
    authDomain: 'surf-para-baixinhos.firebaseapp.com',
    storageBucket: 'surf-para-baixinhos.firebasestorage.app',
    measurementId: 'G-3HPZ3NVEQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEqY-NeMj_RVlws-f9BGRcYVJ0IQ3I-k',
    appId: '1:243663523925:android:f73023dd3ce6e53c7d44dc',
    messagingSenderId: '243663523925',
    projectId: 'surf-para-baixinhos',
    storageBucket: 'surf-para-baixinhos.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIUd5cXGtmnTkk5n2zMwsxA_bcb0J5gl8',
    appId: '1:243663523925:web:2f18b0861f302c927d44dc',
    messagingSenderId: '243663523925',
    projectId: 'surf-para-baixinhos',
    authDomain: 'surf-para-baixinhos.firebaseapp.com',
    storageBucket: 'surf-para-baixinhos.firebasestorage.app',
    measurementId: 'G-DS1WK26VPE',
  );
}
